### ISSUE TITLE
Support for chirpstack.io (ex Loraserver)

### ISSUE THREAD

**Issue by Flackwind** [mcci-catena/arduino-lorawan#135]
Hello, 
I'm just trying to use this library in a Heltec wireless stick (https://heltec.org/project/wireless-stick/), I'm just wondering if is it possible to use this library to interface with chirpstack server (ex Loraserver).

**Comment by terrillmoore** [comment]
Yes, it is, though I've not tried with the Heltec. MCCI has Catena customers who are using ChirpStack successfully. I'm about to add explicit ChirpStack support as part of #136.
