### ISSUE TITLE
Name in library.json must match library name

### ISSUE THREAD

**Issue by frankleonrose** [mcci-catena/arduino-lorawan#38]
https://github.com/mcci-catena/arduino-lorawan/blob/master/library.json#L29

"Catena MCCI Arduino Development Kit" should be "Catena MCCI Arduino Development Kit (ADK)" to match recent change.

**Comment by terrillmoore** [comment]
Sure. I will correct. Since I don't use PlatformIO, can you give us a simple regression test that can be used to check this in CI?

**Comment by terrillmoore** [comment]
Change pushed to branch `issue38`. @frankleonrose can you pull the branch and confirm that it's right before I merge the pull request?
