### ISSUE TITLE
Commit required headers mcciadk_env.h and mcciadk_baselib.h

### ISSUE THREAD

**Issue by frankleonrose** [mcci-catena/arduino-lorawan#7]

**Comment by terrillmoore** [comment]
hm, ok. Looks like I forgot to mention a required library, eh?  [Catnea-mcciadk](https://github.com/mcci-catena/Catena-mcciadk) ...

**Comment by terrillmoore** [comment]
Let me know if this resolves the problem, otherwise we'll re-open...
